### ISSUE TITLE
Support 3D cases

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#1]
## Current handling of Quasi 2D - 3D cases:
To be able to support the 2D/3D coupling in the example [tutorials/CHT/flow-over-plate/buoyantPimpleFoam-fenics](https://github.com/precice/fenics-adapter/tree/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-fenics) we have to allow simulations, where the dimensionality is 3, even though there is no proper support for 3D simulations in the fenics adapter yet. See, for example 

https://github.com/precice/fenics-adapter/blob/9ee798462532979738fdc085d6d827e5295f481d/fenicsadapter/fenicsadapter.py#L152-L153

and

https://github.com/precice/fenics-adapter/blob/9ee798462532979738fdc085d6d827e5295f481d/fenicsadapter/fenicsadapter.py#L310-L311

If someone wants to run a "real" 3D simulation, the adapter does not work. We should either throw an exception in this case or implement a proper 3D treatment.

## Update: 
* Support 3D cases with the new modular design of the adapter.

**Comment by BenjaminRueth** [comment]
We are more and more getting into the situation that not supporting 3D leads to lots of corner cases that we have to catch. Example:

https://github.com/precice/fenics-adapter/blob/4feb7a4a81aebc2a16f699a6c58667d276ff4bdf/fenicsadapter/fenicsadapter.py#L121-L122

This becomes especially painful in the context of 2d/3d coupling. The many `if`s and `else`s in [this example](https://github.com/precice/fenics-adapter/blob/4feb7a4a81aebc2a16f699a6c58667d276ff4bdf/fenicsadapter/fenicsadapter.py#L188-L218) are a nightmare.

I think that creating a real 3d case for the sake of validating our 3d implementation is probably a major task. However, we can already verify many of the required generalizations to go from 2d to 3d via tests (which do not harm in any case).

Therefore, I would suggest the following approach:

* Add tests for the different cases, where a special treatment of a 3d solver is necessary.
* Don't try to come up with a real 3d case (future work).
* Generalize the adapter to 3d.
