### ISSUE TITLE
Support nearest projection mapping

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#10]
To use nearest projection (2nd order) mapping with the FEniCS adapter, we have to exchange connectivity information via the adapter.

**Comment by BenjaminRueth** [comment]
related to https://github.com/precice/tutorials/issues/11

**Comment by IshaanDesai** [comment]
Refer https://github.com/precice/fenics-adapter/pull/42

**Comment by IshaanDesai** [comment]
Adapter now supports nearest-projection mapping after merging https://github.com/precice/fenics-adapter/pull/42
