### ISSUE TITLE
Parallel design introduced bug in PointSource mechanism used in FSI applications

### ISSUE THREAD

**Issue by IshaanDesai** [precice/fenics-adapter#109]
As mentioned in the issue https://github.com/precice/tutorials/issues/131 the re-design of FEniCS-Adapter has introduced a bug which leads to unnatural behaviour in the tutorial case: `FSI/flap_perp_2D/OpenFOAM-FEniCS`. 
The same bug is observed in the tutorial `FSI/flap_perp_2D/SU2-FEniCS/` not in the form of a crash of the `Fluid/` participant but a change in the tip displacement values of the perpendicular flap.

The error on the OpenFOAM side does not occur when the case is run with a previous version of the FEniCS-Adapter: https://github.com/precice/fenics-adapter/commit/d5517625598aec3a896995e3ba49f4df3fa76ee0.
This clearly means something went wrong in the redesigning of the FEniCS-Adapter: https://github.com/precice/fenics-adapter/pull/71

**Comment by BenjaminRodenberg** [comment]
Related to #84. As soon as we know more about the bug, I can try to contribute a test to avoid that we run into the same problem a second time.

**Comment by IshaanDesai** [comment]
The initial impression was that this bug is related to the adapter function `get_point_sources()` but in fact the bug arises from the way data is sampled from a FEniCS function in the function [convert_fenics_to_precice()]:
https://github.com/precice/fenics-adapter/blob/e216dfde1c97627df56b67f96f1340b116574d1c/fenicsprecice/adapter_core.py#L139-L172

The method for sampling data was changed [in the parallel design of the adapter](https://github.com/precice/fenics-adapter/commit/950f6c527420e92919bb06c4455ad921df242fa6#diff-a907482ded9da18225a31c919143625e53b07dd8fd8ed23bad69917be34c3806R139-R172).

Initially the function was directly sampled: `fenics_function(x, y)` but now all the vertex values are obtained by using the FEniCS functionality: `fenics_function.compute_vertex_values()` and then values are sampled from this array. This change was done because direct function sampling does not work in parallel. 

Further investigation on how to resolve this is WIP.

**Comment by BenjaminRodenberg** [comment]
18edb6a7b03708eae8f51c0bab6037fa39f67da2 Introduces a test for exactly this bug. Therefore, 18edb6a7b03708eae8f51c0bab6037fa39f67da2 leads to [failing unit tests](https://github.com/precice/fenics-adapter/runs/1627034499). As soon as this issue is closed the test should pass again.

**Comment by IshaanDesai** [comment]
> [18edb6a](https://github.com/precice/fenics-adapter/commit/18edb6a7b03708eae8f51c0bab6037fa39f67da2) Introduces a test for exactly this bug. Therefore, [18edb6a](https://github.com/precice/fenics-adapter/commit/18edb6a7b03708eae8f51c0bab6037fa39f67da2) leads to [failing unit tests](https://github.com/precice/fenics-adapter/runs/1627034499). As soon as this issue is closed the test should pass again.

The reference output of the tests needs to be modified again for the tests to pass. The updating is done here: https://github.com/precice/systemtests/pull/272
