### ISSUE TITLE
Compute exact solution of HT case for complex interface

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#113]
In https://github.com/precice/fenics-adapter/pull/82#issuecomment-672896370 I provided results for segregated RBF + complex geometry. However, these results can only be obtained, if using the `fenics-adapter/prototyping` setup from the respective revision. I noticed the following lines of code in this setup that we do not have in the original tutorial:

https://github.com/precice/fenics-adapter/blob/433390bea371837bf2a5614c754bb2ecbb5be137/prototyping/heat.py#L206-L210

I do not know why adding these datapoints leads to such a siginificant improvement for the complex geometry. I only observed that removing these additional datapoint significantly increases the error for the complex geometry case.

## Observations on segregated RBF

To understand this I did a few experiment with the segregated RBF interpolation

https://github.com/precice/fenics-adapter/blob/300ab1a60770c72df0978556bd71e57476b67d69/fenicsprecice/expression_core.py#L168-L195

Dropping the mixed and linear terms gives good results for both setups without the need to add additional data (i.e. using https://github.com/precice/tutorials/commit/107c076f2ed65a70cb0cd932387be0c19c0dc667 without modifications). This can be achieved by using the following interpolant:

```
lstsq_interp = lambda x, y, w: w[0] * (x**2) + \
                               w[1] * (y**2) + \
                               w[2] * 0 + \
                               w[3] * 0 + \
                               w[4] * 0 + \
                               w[5]
```

### More experiences, so far

* Generally checking the weights (`print(w)`) gives some more insight.
* Another alternative (with interesting results) is to return the `lstsq_interp` and completely dropping RBF.

## Question

From the example above we see that results can be improved by tuning the `lstsq_interp`. Is there a general `lstsq_interp` (including the linear terms?) that we can use for all cases?

Related: #83

**Comment by BenjaminRodenberg** [comment]
697c401 allows us to get good results for the complex and simple geometry case. However, I do not think that this is a perfect solution, since it requires "expert knowledge".

# Details

Our least squares matrix `A` does not have full column rank for the two cases we are considering. `A` has the columns `1, x, y, x**2, y**2, x*y`. For the simple interface case we have a constant y. Therefore the rank is only 3. For the complex interface case the rank is only 5 (not 6), since we are sampling on a circle (`x**2 + y**2 = r**2`).

My implementation now checks whether new columns are linearly independent and discards them, if they are not. This gives us a unique solution for the weights (I do not really understand why scipy does not complain, if it receives an A that does not have full rank).

However, this solution is hard-coded and requires expert knowledge. Why? Whether we discard the column corresponding to `y` or `y**2` only depends on the order. However, this will in the end determine whether our interpolant is `w[2] * y**2 + ... + 0 * y` or `0 * y**2 + ... + w[4] * y`. These are, of course different interpolants. Looking at the analytical solution, we know which one is better. However, without this knowledge it's just guessing.

@uekerman Does this make sense? Do you have an idea how we can fix this?

**Comment by BenjaminRodenberg** [comment]
https://github.com/precice/tutorials/pull/144 Provides a fix for this problem on the side of the tutorials.

Like discussed above the problem is ill-posed (least squares matrix `A` does not have full column-rank, if we only sample on the circle). Solving this problem in the adapter is not reasonable, because this would mean changing our interpolation routine for the sake of solving an ill-posed problem.

The actual solution for the problem is to add more data such that `A` has full column rank. This means: We have to add one sample that does not lie on the circle. This adds a new row to `A` that is linearly-independent to the previous ones, since it does not lie on the circle (`x**2 + y**2 = r**2` + some shifting around is not fulfilled). This makes the problem well-posed and we obtain the analytical solution.

## On the simple geometry case

Note that also the simple geometry case is ill-posed. All samples lie on a straight line and therefore `A` has only rank `3`. However, in this case we do not care. If we evaluate our interpolant on the line, we get the same values like for the analytical solution (this is what we need). If we evaluate our interpolant somewhere else, we do not get the correct values (but here, we don't care).

## What does this mean for our interpolation routine?

In a practical setup we usually have lower requirements with respect to accuracy. We will not be able to obtain the exact solution and it will (most probably) not be a quadratic form. Therefore this issue still exists, but it becomes a `wontfix`.

**Comment by BenjaminRodenberg** [comment]
Closing this issue as soon as https://github.com/precice/tutorials/pull/144 is merged.

**Comment by uekerman** [comment]
Wouldn't it be a solution to simply add a regularization term to the least-squares fitting? 
||Ax - b ||_2 + lambda * ||x||_2 -> min 
Then the unused coefficients just become 0.

**Comment by BenjaminRodenberg** [comment]
> Wouldn't it be a solution to simply add a regularization term to the least-squares fitting?
> ||Ax - b ||_2 + lambda * ||x||_2 -> min
> Then the unused coefficients just become 0.

I checked the scipy documentation and found out that [`scipy.linalg.lstsq`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lstsq.html) uses LAPACK's [gelsd](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines/lapack-least-squares-and-eigenvalue-problem-driver-routines/linear-least-squares-lls-problems-lapack-driver-routines/gelsd.html), which determines the *minimum norm* solution for a least-squares problem. Meaning: `Ax = b` is underdetermined the `x` with `||x||_2 -> min` is used as solution. As far as I understand this is identical to the kind of regularization you propose above.

This closes this issue, since I do not see a reasonable way how we could make sure that we get the `x` that we actually want for an underdetermined system.

**Comment by BenjaminRodenberg** [comment]
Another note: I was wondering why the simple geometry case does not fail. Remember: It's also underdetermined.

For both cases (simple and complex) we get the correct values (= identical to exact solution) on the coupling interface (straight line and circle). For the simple case the straight line is exactly represented in the discrete FEM world, while the circle is only approximated. This results in getting the correct boundary conditions for the straight line (because the data is correct), but getting boundary conditions that are slightly off for the circle (data on circle is correct, but we don't evaluate on the circle, but on a polygon, where the data is also slightly off).
