### ISSUE TITLE
Small error at boundaries in fenics-fenics tutorial

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#13]
Plotting the L2 error on the domain of the tutorial [HT/partitioned-heat/fenics-fenics](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) shows a small error at the coupling interface, if we are close to the boundary.

![smallerroratboundary](https://user-images.githubusercontent.com/5740604/49167496-c5abff80-f335-11e8-92e1-9b77fd43c766.png)

Inside the domain everything looks fine and the error also does not grow over time. If the resolution is reduced, the error gets smaller. These are generally good things. The error does not get smaller, if we reduce the tolerance of the coupling.

**What's wrong with this error?** We should be able to recover the exact solution in this example case:

* The analytical solution is first order in time and second order in space. Our discretization (implicit Euler/linear FEM) should be able to recover this solution. For details, see the [FEniCS tutorials book, p.40)[https://fenicsproject.org/tutorial/].
* The meshes are matching and therefore no mapping is necessary (which might introduce an error; see #11 )

**Where does this error come from?** Possible candidates:

* Wrong computation of the flux at the interface, since this is still a point where I am not 100% sure that we are doing everything correctly
* Wrong treatment of the point, where coupling interface and outer boundary meet.

The results from above can be recovered using https://github.com/precice/tutorials/commit/f9fe1201e1a9f648a2c325e04307d16bad5197e2 and https://github.com/precice/fenics-adapter/commit/a006b304325eabc9f15dba3d7c3b40d4a6a3b1bb.

**Comment by BenjaminRueth** [comment]
If we use
```
         <relative-convergence-measure data="Flux"        mesh="NeumannNodes" limit="1e-10"/>
         <relative-convergence-measure data="Temperature" mesh="NeumannNodes" limit="1e-10"/>
```
in `precice-config.xml`, we can furtherly reduce the error.

![error](https://user-images.githubusercontent.com/5740604/49259104-4521f780-f438-11e8-9d17-9e01b8798472.png)

Furtherly reducing to `limit=1e-13` allows us to reach machine precision:

![error](https://user-images.githubusercontent.com/5740604/49259280-0fc9d980-f439-11e8-978d-c29d74d522a4.png)

**Comment by uekerman** [comment]
We could then probably close this issue, right? It's a coupling error, no mapping error and no wrong boundary condition error. 
And if you want to reach machine precision, you also need to let the coupling loop converge until there. This behavior, I would expect.

**Comment by BenjaminRueth** [comment]
For this test case, we can close the issue, but the solution that I mentioned above is not implemented in a general way yet (only coupling boundaries that are parallel to the y axis work). Therefore, I would suggest to keep this issue open until we have found a general solution and this solution is merged into fenics-adapter/master. The non-general solution from above is only on a branch (https://github.com/precice/fenics-adapter/compare/LinearInterpolationWithActiveExtrapolation) currently.

**Comment by BenjaminRueth** [comment]
[`LinearInterpolationWithActiveExtrapolation`](https://github.com/precice/fenics-adapter/compare/LinearInterpolationWithActiveExtrapolation) is quite old and not in sync with master and therefore is deleted. 

Use [`UsingExtrapolation`](https://github.com/precice/fenics-adapter/tree/UsingExtrapolation) instead. The corresponding tutorials branch, is also called [`UsingExtrapolation`](https://github.com/precice/tutorials/tree/UsingExtrapolation).

**Comment by BenjaminRueth** [comment]
Using the approach introduced in https://github.com/precice/tutorials/commit/3d836fa4b112ffe0661fba43d6f6021f62f36370 we do not need extrapolation anymore, since the corner nodes can be included in the coupling domain. This is probably the proper definition for the boundary conditions, anyway.

However, we cannot reach machine precision anymore. The source of error still lies at the corners.

![Screenshot from 2019-07-20 14-40-35](https://user-images.githubusercontent.com/5740604/61578802-64bb7c80-aafc-11e9-9e9b-a5c5439408ad.png)

One possible explanation is that the derivative of the Dirichlet Boundary condition at the top and bottom is not consistent with the flux being computed at the corners.

**Comment by BenjaminRueth** [comment]
For some context see: https://github.com/precice/tutorials/commit/3d836fa4b112ffe0661fba43d6f6021f62f36370#r36181420

**Comment by BenjaminRueth** [comment]
I cannot observe significant inaccuracies anymore:

![image](https://user-images.githubusercontent.com/5740604/89569683-5df5c980-d825-11ea-8657-32ded2381b6d.png)

Based on https://github.com/precice/fenics-adapter/pull/82/commits/8f28a854cb95056f9813fbf52d0850dcd18971cb. As soon as #82 is merged and the tutorials are updated, we can close this issue.

**Comment by BenjaminRueth** [comment]
With the `SegregatedRBFInterpolationExpression` introduced in #83, we have a general and working solution.
