### ISSUE TITLE
Outdated documentation regarding actions

### ISSUE THREAD

**Issue by DavidSCN** [precice/fenics-adapter#139]
https://github.com/precice/fenics-adapter/blob/69a16bdf9d237e512e2e1ae9ef4ed1bb983ea5b9/fenicsprecice/fenicsprecice.py#L560

The referenced link doesn't work and is outdated (amongst others in this file). In particular, I'm looking for the action `actionWriteInitialData`, but I couldn't find any documentation on this. Is it available at all?

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/precice/fenics-adapter/commit/f517f2c27b3b2ccf0f0c90359253079ff976833e
