### ISSUE TITLE
Use 2nd order mapping for FEniCS-FEniCS example

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#14]
In https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics we currently use ```nearest-projection```. Since no connectivity infomation is given, this falls back to (1st order) ```nearest-neightbor```.

We use a linear finite element discretization (2nd order error). Therefore, we should also use a 2nd order mapping. Otherwise, the discretization error (probably) drops to 1st order due to the mapping.

**Bonus:** Thorough study on this expected behaviour would be interesting.

**Comment by uekerman** [comment]
It's not surprising that the error for a 20/10 combination is smaller than the error for the 21/9 combination. 20/10 is almost matching. Let's take at the 21/9 example as our non-matching baseline.

**Comment by IshaanDesai** [comment]
A convergence study for the tutorial: https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics is done for the mappings `nearest-neighbor` (NN) and `nearest-projection` (NP). Completely non-aligned interface cases were used (5/11, 9/21, 19/41 and 39/79) to ensure that NP-mapping is fully utilised. Results:
![simple_interface_convergence](https://user-images.githubusercontent.com/44898158/67185237-aacaf980-f3e5-11e9-911d-340596d7b7cd.png)
NP mapping is clearly better performing than NN mapping for non-aligned interface cases.
