### ISSUE TITLE
Homogenize citation information

### ISSUE THREAD

**Issue by ajaust** [precice/fenics-adapter#140]
I think we should homogenize the citation section, see https://github.com/precice/fenics-adapter/blob/69a16bdf9d237e512e2e1ae9ef4ed1bb983ea5b9/README.md?plain=1#L76, in the README a bit. To me it focuses a bit too much on preCICE as it mentions the full citation information and also the it funding source etc. For the citation of the adapter and FEniCS it only refers to some external homepage where it is actually hard to cite us properly.

I would make the following suggestions:

- We decide how we should present the citation of the FEniCS-preCICE adapter and its dependencies, namely preCICE and FEniCS. I would vote for linking to the citation information of their project pages. For FEniCS-preCICE we link to the "How to cite" section on the preCICE homepage as it is done now. This would mainly mean I would shorten the preCICE part in the README. This way we only have to update the citation information for the adapter at one place.
- I would redo the ["how to cite us"](https://precice.org/adapter-fenics.html#how-to-cite) section in the documentation. At the moment it is not very intriguing to cite as it looks like this
  > If you are using our adapter, please consider citing our paper “FEniCS-preCICE: Coupling FEniCS to other Simulation Software” [1].

  One cannot even click on the `[1]` to get to the citation. I think I would get rid of the `[1]` and `[2]` on this page or at least make the clickable as it feels unnatural on a homepage at the moment.
  My goal would be:
  - Reformat the citation in this subsection such that one can copy and paste easily if necessary to put it into some slides/document. 
  - Add a bibtex file for easy integration LaTeX document.
  - Ideally this would end up in one of these citation blocks one finds on the [preCICE homepage](https://precice.org/publications.html#how-to-cite-precice).
- Make sure that the references are up to date.

I could make a first draft of the changes.

**Side note** To me it is not clear how this section will be affected by #137 as this PR will only affect citation of the adapter, but not the dependencies.

**Comment by ajaust** [comment]
The PR https://github.com/precice/precice.github.io/pull/97 is related to this issue.

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/precice/precice.github.io/pull/97
