### ISSUE TITLE
Compare nearest neightbor, nearest projection and RBF mapping

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#15]
Would be nice to have a thorough comparison of the two mappings to validate the theory (1st/2nd order...). As soon as https://github.com/precice/fenics-adapter/issues/10 is complete, it should be easy to compare the different mappings. The [fenics-fenics tutorial](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) provides a good scenario for testing.

**Comment by BenjaminRueth** [comment]
@IshaanDesai do you think we can close this issue? A large part of the comparison of the different schemes has already been done in #42.

**Comment by BenjaminRodenberg** [comment]
This issue can be closed. The simple and complex geometry case of the heat transport tutorial work nicely with second order. See #115.
