### ISSUE TITLE
recommended install fails under Ubuntu

### ISSUE THREAD

**Issue by ng0177** [precice/fenics-adapter#164]
This error appears under Ubuntu 23.04
```
$ pip3 install --user fenicsprecice
error: externally-managed-environment
```

**Comment by BenjaminRodenberg** [comment]
@IshaanDesai I did not follow the discussion on discourse. Are there any updates or solutions we could offer here?

**Comment by BenjaminRodenberg** [comment]
@NiklasVin I think this is mainly a documentation issue that we can resolve by updating the `README.md`. For more recent `pip` version it is generally recommended to use `venv` (we are introducing the corresponding changes in the tutorials currently https://github.com/precice/tutorials/issues/547)
