### ISSUE TITLE
Support `numpy >= 2` ?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#176]
We currently do not support `numpy >= 2`. I, consequently, restricted numpy to `numpy < 2` in #175. Ensuring compatibility for newer numpy versions (and occasionally dropping numpy 1 support) is definitely a future todo.

Remark:

* Since FEniCS (without the x) is at it's end of life, we might also just stay with numpy version 1 and make this issue a `wontfix`.
* I'm currently not sure if this is actually an issue with the FEniCS adapter or with the python bindings. (we don't have any restrictions on numpy in the python bindings but I'm also not sure whether we are actually testing numpy 2; see https://github.com/precice/python-bindings/blob/45b3ecc241e86ef1509338a0efc725f822c09839/setup.py#L140)

**Comment by BenjaminRodenberg** [comment]
Note that we are currently fixing support for numpy >= 2 in pyprecice (https://github.com/precice/python-bindings/pull/218). Therefore, it might be possible to easily support numpy >= 2 here as well. This requires some testing but would also give us additional flexibility for downstream projects.

**Comment by NiklasVin** [comment]
>     * Since FEniCS (without the x) is at it's end of life, we might also just stay with numpy version 1 and make this issue a `wontfix`.

I tried to solve the plain heat equation (so no partitioning) with FEniCS and numpy version `2.0.0` and got the following error: `ValueError: could not convert string to float: 'np.float64(-1.0)'`.
In [this discussion on the FEniCS discourse](https://fenicsproject.discourse.group/t/could-not-convert-string-to-float-error-when-defining-functionspace/15528), the same error occured and it seems like the numpy version is the issue. 
Hence, I would say that supporting `numpy >= 2` for the fenicsprecice adapter isn't possible, or makes no sense at least.

**Comment by BenjaminRodenberg** [comment]
Closing this issue. This is another argument for prioritizing FEniCS-X on the long run.
