### ISSUE TITLE
Fix issue with non-matching subcycling

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#20]
If we use subcycling, we can have one of the following setups:

* **matching:** timestep size of FEniCS perfectly fits the windows size of preCICE. Example: fenics_dt = 0.1, precice_dt = 1. Resulting in timesteps at [0,0.2,0.4,0.6,0.8,1]
* **non-matching:** timestep size of FEniCS has to be reduced for the last timestep to fit into the window. Example: fenics_dt = 0.3, precice_dt = 1. Resulting in timesteps at [0,0.3,0.6,0.9,1]

For both setups the error increases compared to the setup without subcycling (this makes sense, since timestepping is strongly affected, if no proper waveform relaxation is used). However, for the **non-matching** case, the error is quite high compared to the **matching** case. 

The size of the error seems not to be related to the timestep size for the non-matching case (if fenics_dt for the non-matching case is smaller than fenics_dt for the matching case, we still have higher error for the non-matching case). This makes me assume that there is another issue with non-matching subcycling besides the fact that we should use proper waveform relaxation to obtain the exact solution. What is this additional issue?

**Comment by BenjaminRueth** [comment]
For example code see https://github.com/precice/tutorials/blob/checkpointing/HT/partitioned-heat/fenics-fenics/heat.py#L44 and https://github.com/precice/tutorials/blob/checkpointing/HT/partitioned-heat/fenics-fenics/heat.py#L136

**Comment by BenjaminRodenberg** [comment]
This was actually a bug in the tutorial. See https://github.com/precice/tutorials/pull/383.
