### ISSUE TITLE
Update python API to new version

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#25]
See [Changelog v1.4.0](https://github.com/precice/precice/blob/develop/CHANGELOG.md).

**Comment by BenjaminRueth** [comment]
This is issue is basically identical to https://github.com/precice/elastictube1d/issues/10.

**Comment by RafalKulaga** [comment]
@BenjaminRueth I pushed updated `fenicsadapter.py` to api_update branch. I tried it with HT scenario and all worked as before. Can you please have a look?
