### ISSUE TITLE
Handling of vector-valued coupling data

### ISSUE THREAD

**Issue by RafalKulaga** [precice/fenics-adapter#26]
For structural solver handling of vector function space is required, however this is currently not supported by the `fenicsadapter.py` . At first it seemed that it can be fixed easily, as there are Vector equivalents of Scalar functions in `PySolverInterface.py` (e.g. `writeBlockScalarData()` and `writeBlockVectorData()`), but actually there is no difference in the body of these functions, hence it does not help.

Anyway, I am first going to change from 'PySolverInterface.py' to 'precice' and then try to cope with this issue (https://github.com/precice/fenics-adapter/issues/25).

**Comment by uekerman** [comment]
I changed the name of the issue. Did I get it right, is that what you want to do?

What do you mean by?

> ... but actually there is no difference in the body of these functions, hence it does not help.

**Comment by RafalKulaga** [comment]
Yes.

I should now refer to `precice.pyx` functions and not `PySolverInterface` due to #25. I just mean that simple changing from e.g. `write_block_scalar_data()` to `write_block_vector_data()` in `fenicsadapter.py` does not help. Using vector-valued functions yields the same error in both cases. This is understandable as the implementation of "scalar" and "vector" version of `read` and `write` does not differ (it is the same code). Please compare line 259-281 and 300-322 of [`precice.pyx`](https://github.com/precice/precice/blob/develop/src/precice/bindings/python/precice.pyx).

I will push the draft of structural solver, so the error (_TypeError: only size-1 arrays can be converted to Python scalars_) can be reproduced.

**Comment by uekerman** [comment]
> This is understandable as the implementation of "scalar" and "vector" version of `read` and `write` does not differ (it is the same code)

Well, it does call two different preCICE methods that do different things. Probably, I understand better what you mean when you push the draft of the structural solver. 

Also for the vector-valued case: `len(value_indices)` != `len(values)`. 

Still needs `values` needs to be one-dimensional array (of size `numberOfVertices` times `dimensions`). Maybe you are looking for the method [ravel])https://www.geeksforgeeks.org/numpy-ravel-python/) ?

**Comment by RafalKulaga** [comment]
@uekerman Thanks, I did not know that it must be one-dim array. Using `ravel` helped, but just to make sure: from [ [u1, v1], [u2, v2] ...] form we want [ u1, v1, u2, v2, ...] and not [ u1, u2, ... v1, v2, ... ], right?

The issue cannot be closed yet though, there are further modifications in `fenicsadapter.py` required.

**Comment by uekerman** [comment]
> but just to make sure: from [ [u1, v1], [u2, v2] ...] form we want [ u1, v1, u2, v2, ...] and not [ u1, u2, ... v1, v2, ... ], right?

Exactly! See also the [API documentation](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html)

**Comment by BenjaminRueth** [comment]
Closed. Vector valued data is supported since #38 has been merged.
