### ISSUE TITLE
Move heat flux computation into a CHT module

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#3]
In the examples ```fenics-fenics``` and ```buoyantPimpleFoam-fenics``` the flux computation is basically identical, since the examples deal with identical physics. 

* in ```fenics-fenics``` : https://github.com/precice/tutorials/blob/master/HT/partitioned-heat/fenics-fenics/heat.py#L65
* in ```buoyantPimpleFoam-fenics```: https://github.com/precice/tutorials/blob/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py#L65

The solver uses Dirichlet BC on the whole boundary, while heat flux (Neumann BC) is computed in a post-processing step. Heat flux computation is problem dependent, but is not a required feature to solve the actual problem. We only need heat flux for coupling. 

Therefore, we should move this functionality into a common CHT (Conjugate Heat Transfer) module (see [OpenFOAM Adapter](https://github.com/precice/openfoam-adapter)) to avoid code duplication and to ease reuse for coupled simulations with the same coupling physics (CHT), but a different solver (e.g. different boundary conditions, modeling...).

**Comment by BenjaminRueth** [comment]
I opened a thread [here](https://fenicsproject.discourse.group/t/compute-gradient-of-scalar-field-on-boundarymesh/1172), since I am still not convinced by our current approach for computing the heat flux.

**Comment by BenjaminRueth** [comment]
In https://github.com/precice/tutorials/commit/3d836fa4b112ffe0661fba43d6f6021f62f36370 I changed the approach for heat flux computations. The approach before was less understandable and general. However, the new approach is less accurate and we cannot reach machine precision anymore (like described in https://github.com/precice/fenics-adapter/issues/13#issuecomment-443036244). The source of the error seems to be at the corners.

**Comment by BenjaminRueth** [comment]
Related: https://github.com/precice/fenics-adapter/issues/13#issuecomment-513464309

**Comment by BenjaminRueth** [comment]
Additionally, we have to make sure that the *normal* heatflux is considered. A shortcoming of the current adapter version becomes obvious, looking at [this code](https://github.com/precice/tutorials/blob/02d474cf42c89ba1d178580ad4f89b3bdc007c43/HT/partitioned-heat/fenics-fenics/heat.py#L266-L267), where the sign of the flux field has to be flipped, if we are considering the flux at the edge with normal pointing in negative direction.

**Comment by MakisH** [comment]
I am not sure we can avoid the minus. At the end of the day, when we couple two solvers, both have normal vectors pointing outside, so one needs to assume the flipping somewhere.

I think the best would be that we do the flipping in preCICE, e.g. using actions. In any case, we should document it everywhere.

**Comment by BenjaminRueth** [comment]
I will close this issue now, because I do not think that we can apply the design to the FEniCS adapter like for the OpenFOAM adapter. In the OpenFOAM adapter introducing modules for different physics has turned out a good decision. For the FEniCS adapter this is still not clear. 

We can reopen this issue, if we have to reconsider the topic "modules" for the FEniCS adapter.
