### ISSUE TITLE
Implement higher (2nd) order time-stepping scheme in fenics example

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#30]
[Our current examples](https://github.com/precice/tutorials/tree/master/partitioned-heat-conduction) only use the implicit Euler scheme (1st order). How do we properly implement higher order time stepping schemes in FEniCS? Especially the implementation of time dependent boundary conditions is unclear.

[This post](https://fenicsproject.org/qa/2513/how-to-define-a-given-explizit-runge-kutta-method-correctly/) gives some first ideas regarding trapezoidal rule in FEniCS.

**Comment by BenjaminRueth** [comment]
[Here](https://github.com/precice/elastictube1d/blob/master/PythonTube/thetaScheme.py) we use the theta scheme for relizing 2nd order timestepping. This code is **not using FEniCS** and the system is written down explicitly (system matrix, not weak form).

**Comment by PeterMeisrimel** [comment]
I have a working second order in time implementation (for time-dependant boundary conditions), it is currently based on a C++ interface of FEniCs, but I will look into putting it in Python as well.

**Comment by BenjaminRueth** [comment]
Trapezoidal rule is used [here](https://gitlab.lrz.de/precice/ijnme2019-experiments/blob/master/Conjugate%20Heat%20Transfer/approximation_order_in_time/g_pol/run/heat.py#L178-179).

**Comment by BenjaminRodenberg** [comment]
In [Nikola Wullenweber's thesis](https://mediatum.ub.tum.de/node?id=1621360) there is some further information about higher-order timestepping with the heat equation in FEniCS.

**Comment by BenjaminRodenberg** [comment]
This issue was completed via https://github.com/precice/tutorials/pull/415
