### ISSUE TITLE
Refactor adapter for clearer control flow

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#33]
https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L244-L248

--> Create Function `restore_solver_state_from_checkpoint`

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L250-L252

--> Create Function `advance_solver_state`

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L255-L261

--> Create Function `save_solver_state_to_checkpoint`

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L254

--> add assertion after this line `assert(not solver_state_has_been_restored_before)`, since this control flow is invalid.

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L233

--> add `if is_read_data_available():`

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L235

--> add `if is_write_data_required():`

---

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L282-L289

is code duplication of 

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L235

https://github.com/precice/fenics-adapter/blob/1b8a278df28330b3354b443e5813f73438fe6200/fenicsadapter/fenicsadapter.py#L254-L261

**Comment by BenjaminRueth** [comment]
Use the names from this flowchart: [usage.pdf](https://github.com/precice/fenics-adapter/files/3121702/usage.pdf)

**Comment by uekerman** [comment]
As discussed between @BenjaminRueth and me: The flowchart still has several inconsistencies compared to the adapter example in the wiki that we need to fix.

**Comment by BenjaminRueth** [comment]
Issue is closed by #59.
