### ISSUE TITLE
How can we create Expression / function representation for boundary conditions properly?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#4]
Our FEniCS adapter uses Expressions to define Dirichlet and Neumann boundary conditions. Since preCICE only provides nodal data, we implemented the class [CustomExpression](https://github.com/precice/fenics-adapter/blob/master/fenicsadapter/fenicsadapter.py#L21) to be able to create a functional representation (an Expression) from nodal data.

In our implementation RBFs are used for interpolation (see [eval function](https://github.com/precice/fenics-adapter/blob/master/fenicsadapter/fenicsadapter.py#L52)). However, this approach is not ideal when considering the whole coupled simulation from a broader perspective: 

preCICE already uses interpolation to map data from the coupling partner's mesh to the FEniCS mesh (if the meshes are not matching). However, the interpolant is hidden in preCICE and, therefore, we have to perform an additional interpolation step on the FEniCS side to create an interpolant that may be used by FEniCS for defining boundary conditions.

Some first ideas:

* Does FEniCS allow defining boundary conditions / expressions from nodal data instead of functions?
* Can we directly access the interpolant inside preCICE to avoid the additional interpolation step?

**Comment by BenjaminRueth** [comment]
If we take a look at https://github.com/precice/tutorials/issues/13#issuecomment-443029988, we see that RBF functions are not necessarily the ideal choice for interpolation. 

If we use linear interpolation instead, we need connectivity information and we have to generalize the implementation in https://github.com/precice/fenics-adapter/commit/f69a016803e7a2d59e25c7248ef6653a9efcaf61 to support arbitrary coupling interface. Currently only straight boundaries that are parallel to the y-axis are supported.

Using linear interpolation with connectivity information allows us to use the nearest projection mapping, in the end. This will be helpful for working on https://github.com/precice/tutorials/issues/11.

**Comment by uekerman** [comment]
> Can we directly access the interpolant inside preCICE to avoid the additional interpolation step?

Not really. Also, another problem then would be how to convert this interpolant to a description that FEniCS understands. 

> Does FEniCS allow defining boundary conditions / expressions from nodal data instead of functions?

Can we ask on a FEniCS mailing list? This should be a quite natural feature. Also needed if you want to read boundary conditions from a file etc., so others should also have this problem. 

This should not be something to implement in the adapter, but directly in FEniCS.

**Comment by BenjaminRueth** [comment]
Another possible approach for creating an interpolant from point data: use [(generalized) moving least squares](https://en.wikipedia.org/wiki/Moving_least_squares). See work of [Paul Kuberry](http://paulkuberry.com/research.html) for more details.

**Comment by BenjaminRueth** [comment]
If we create a piecewise linear interpolant (like e.g. [here](https://github.com/precice/fenics-adapter/blob/f6caecb403041c5d006f8c37adaf5905ff652ba1/fenicsadapter/fenicsadapter.py#L62-L63)), this has a major problem: The FEniCS solver always "sees" a piecewise linear function, even if the point data that we interpolate does not originate from such a function. If we, for example, use a second or higher order function space as finite element basis (see [here](https://github.com/precice/tutorials/blob/245c259d2235176242e45d5a61229a15f81e7dfe/HT/partitioned-heat/fenics-fenics-core/heat.py#L182)), this will lead to problems like an incorrect flux computation. We should use higher order interpolation instead (see [here](https://github.com/precice/fenics-adapter/blob/3881299f45c2dee0a60209194ec283e25b4ba6b3/fenicsadapter/core.py#L131-L136)) to avoid problems.

**Comment by BenjaminRueth** [comment]
In Nutils, we can simply use the Gauss Points of the function. This completely avoids an additional interpolation step inside the adapter. See [here](https://github.com/precice/tutorials/blob/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py#L58).

**Comment by BenjaminRueth** [comment]
The fenics-adapter now provides means for the user to choose between the two strategies *RBF interpolation* and *polynomial interpolation* (https://github.com/precice/fenics-adapter/commit/7afb0e02d7dfce1d93db6a90fe03ffc1c0f92bd7).

**Comment by BenjaminRueth** [comment]
In https://github.com/precice/fenics-adapter/pull/38 FEniCS' `PointSource` has been used for correctly dealing with point sources (e.g. nodal forces) that are mapped in a conservative fashion. This is an alternative strategy to the interpolation of point data as explained above. Note that the approach based on interpolation gave wrong results and the approach using a `PointSource` is the correct on.

More details on this will follow in the thesis of @richahert

**Comment by BenjaminRodenberg** [comment]
This issue is closed by #83. @richahert 's thesis can be found here: https://mediatum.ub.tum.de/node?id=1520579
