### ISSUE TITLE
Naming of the adapter package is inconsistent

### ISSUE THREAD

**Issue by ajaust** [precice/fenics-adapter#43]
Hi,

I found the following inconsistency with naming of the package.

## Short version

The adapter is sometimes referred to as `fenics-adapter` and sometimes as `fenicsadapter`. It would be nice to stick if one name. I would prefer `fenicsadapter` as this is also the name of the module in Python.

## Detailed description
The adapter is sometimes referred to as `fenics-adapter`, see for example the name of this repositiory. However the package is called `fenicsadapter` so in your code you have something like
```python
from fenicsadapter import Adapter, ExactInterpolationExpression, GeneralInterpolationExpression
```

I was a bit confused about that when I wanted to remove the adapter using `pip`. I only got a warning about the package not being instaled:
```bash
pip3 uninstall fenicsadapter
WARNING: Skipping fenicsadapter as it is not installed.
```
Instead I had to do
```bash
pip3 uninstall fenics-adapter
```
I expected that the adapter would be uninstalled via the first command without the dash.

In my local `~/.local/lib/python3.6/site-packages/` I find `fenics_adapter-0.1.dist-info/` and `fenicsadapter/` that both refer to the adapter if I understand correctly?! I guess that has to be like it.

Thanks for your work!

**Comment by BenjaminRueth** [comment]
I totally agree. Let's use the name `fenicsadapter` consistently. However, it might take some time until I will be able to actually apply the changes.

**Comment by uekerman** [comment]
I guess this comes from the fact that all our repos on GitHub are called `solver-adapter`. This, we should also keep consistent. 

But this does not mean that we need to use the same name for the "adapter object". Here, we should stick to the style of the solver. In OpenFOAM, we use `preCICE_Adapter`. Would this also makes sense here? `preciceadapter`?

**Comment by ajaust** [comment]
I was thinking a bit more about the naming "issue" and I understand that it is hard to find a good solution that satisfies everyone. Different programming languages prefer different coding/naming styles and conventions. I guess for the Python bindings and adapter to be used in Python it makes sense to follow the pep style guide.

The main point "bothering" me when opening this issue was that
```bash
pip3 uninstall fenicsadapter
```
did not uninstall the module even though it is called `fenicsadapter. For example, one uses it in the code via `import fenicsadapter`. I guess that would be easy to fix.

Regarding the future naming of the adapter and the adapter it is more tricky. I think the name of the repository is fine in general. I just wanted to mention that there are differences between the namings. 

Regarding the name of Python module I don't know what makes most sense. I guess that is something you have to find out. `preciceadapter` could be too vague. Would it be an adapter for `preCICE+Python`, `preCICE+FEniCS`, `preCICE+Nutils`, `preCICE+SomePythonLibrary`? It could be a problem when you have adapters to more than one Python library/interface.

`fenicsadapter` on the other hand gives no (obvious) hint towards `preCICE`. So somebody reading the code without knowing about the purpose of the code `fenicsadapter` might be too vague again as it does not refer to `preCICE` in any way. However, putting `fenicsadapter` into Google etc. gives this repository as first result though which is nice. ;)

What would be alternatives?
Calling the bindings `precice` and the adapter `fenicsprecice`, `precicefenics`, `precicefenicsadapter`? At what point is it too long and too descriptive?

I will leave that here... so far I don't have any good answers, but maybe it helps you in some way.

**Comment by BenjaminRueth** [comment]
So let's use `fenicsadapter` consistently. I will push this in a moment.
