### ISSUE TITLE
Name of Attribute seems to be wrong 

### ISSUE THREAD

**Issue by moaxm** [precice/fenics-adapter#44]
Shouldn't this attribute be named "_read_function_type"?

https://github.com/precice/fenics-adapter/blob/721dac5a282bf833af436356355a131da84f8663/fenicsadapter/fenicsadapter.py#L282

**Comment by BenjaminRueth** [comment]
I agree. This looks wrong. We will check it. Thank you for opening this issue!

**Comment by IshaanDesai** [comment]
This is now resolved in the [master branch](https://github.com/precice/fenics-adapter/blob/master/fenicsadapter/fenicsadapter.py#L282)
