### ISSUE TITLE
Use a config file to configure the adapter

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#5]
For better agreement with the design of the OpenFOAM adapter we should use a config file to configure the FEniCS adapter instead of hardcoding parameters (or handing them over using the command line).

An example config file of the OpenFOAM adapter can be found [here](https://github.com/precice/openfoam-adapter/blob/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Fluid/precice-adapter-config.yml). We should follow a similar strategy for the FEniCS adapter. 

*sidenote:* Each participant has its own config file for its respective adapter. This means, for example, for the [FEniCS-FEniCS tutorial](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) that we need two config files - one for the Dirichlet, one for the Neumann solver. Compare to the [OpenFOAM-OpenFOAM test case](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam).

**Comment by MakisH** [comment]
Using a python script for the configuration itself would be powerful, but maybe even overkill, as the user may do "hacky things", even by mistake. It would be very easy to implement, though. However, it would be difficult to maintain.

**Comment by BenjaminRueth** [comment]
Is there a human-readable file format that is common in the python community?

**Comment by BenjaminRueth** [comment]
I found a [list on wikipedia](https://en.wikipedia.org/wiki/Comparison_of_data_serialization_formats) where different file formats for data serialization are collected. This might be helpful as a starting point for our research. 

However, on this list JSON and XML are claimed to be human readable... about JSON one can argue, but XML is not the kind of "human-readable" that I have in mind. YAML is from my point of view a really nice file format, but @MakisH already mentioned the technical problems that come with YAML. 

My wishlist for the perfect file format would be the following:

* as simple as YAML
* as easy to get running in python as JSON. (assuming it already comes shipped with python; see https://github.com/precice/fenics-adapter/issues/5#issuecomment-442377518)

**Comment by RafalKulaga** [comment]
Regarding the [#5 (comment)](https://github.com/precice/fenics-adapter/issues/5#issuecomment-442377518)  `python3` comes with built-in package `json`. I found an [article](https://realpython.com/python-json/) giving facts and summarizing essentials about `json`. I tried reading data from `json` file and it was pretty straightforward.

In terms of human-readability assessment, I would say it is quite subjective. For me `json` is easy to read unless the data structure is not too "deep".  Also, in my opinion, priority should be to minimize the number of additional dependencies.

@uekerman I checked FEniCS documentation for any traces of config files.  In all tutorials they use `xml` files but that is mainly for geometry data. Also, there is [one tutorial ](https://fenicsproject.org/docs/dolfin/1.3.0/python/demo/documented/tensor-weighted-poisson/python/documentation.html) where they generate coefficients and save them to `xml` and read afterwards. In addition, FEniCS has [`Parameters class`](https://fenicsproject.org/olddocs/dolfin/1.6.0/python/programmers-reference/cpp/common/Parameters.html), and here ([link](https://github.com/FEniCS/dolfin/tree/master/demo/undocumented/parameters/python)) they also use `xml`. Finally, this [project](https://arxiv.org/abs/1602.03643) seem to be using `.py` to manually change the parameters. Nevertheless, I don't see any reasons against using `json`.

**Comment by uekerman** [comment]
I have a slight tendency towards `xml` or `py`, but also no strong opinion against `json`. Maybe data serialization is the wrong buzz word.

**Comment by BenjaminRueth** [comment]
closed by #22 and https://github.com/precice/tutorials/pull/18
