### ISSUE TITLE
Use new python bindings precice_future

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#50]
The fenicsadapter still uses the [old python bindings](https://github.com/precice/precice/tree/develop/src/precice/bindings/python):

https://github.com/precice/fenics-adapter/blob/1ccab476e3923b34daf274e365ad777f9411569f/fenicsadapter/fenicsadapter.py#L16

We should update this to using the [new python bindings](https://github.com/precice/precice/tree/develop/src/precice/bindings/python_future). Make sure to use the following import statement, since the name of the python binding will change soon and this will avoid future code changes:

```
import precice_future as precice
```

**Comment by BenjaminRueth** [comment]
Related issue that is addressing a different branch #48, since in `precice_future` the data layout for read/write data has changed.

**Comment by IshaanDesai** [comment]
Handled in https://github.com/precice/fenics-adapter/pull/52

**Comment by BenjaminRueth** [comment]
Closed, since #52 is merged.
