### ISSUE TITLE
Fix NP with 2D/3D mapping

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#53]
Currently, we cannot use the [CHT tutorial](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) with nearest projection (NP), since 2D-3D mapping is not covered. Until this bug is fixed, we deactivate NP and use nearest neighbour as default.

**Comment by BenjaminRueth** [comment]
@IshaanDesai can we close this issue? I am wondering, since we are using NP as default now.

https://github.com/precice/fenics-adapter/blob/1e675e0b3597b9786993e6a2ed3e2c226d8f9b26/fenicsadapter/fenicsadapter.py#L458

I think issue this is also related to https://github.com/precice/systemtests/issues/81, since is causing problems (?). A test would help us to know exactly.

**Comment by IshaanDesai** [comment]
I just checked the workflow and we we introduced the NP flag `use_nearest_projection=True` to resolve this error but then found the edge duplicacy and resolved that and merged https://github.com/precice/fenics-adapter/pull/54. I concede that we should have resolved this issue in that PR, will open a quick PR after figuring out a solution for this issue.

**Comment by IshaanDesai** [comment]
CHT tutorial with [buoyantPimpleFoam and FEniCS](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) works with NP mapping in `fenics-adapter`
