### ISSUE TITLE
Consistently use numpy style docstring

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#66]
See https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by IshaanDesai** [comment]
As we are making major changes to the design of the adapter in https://github.com/precice/fenics-adapter/pull/59 should the consistent numpy style docstring documentation be done there as part of the same PR?

**Comment by BenjaminRueth** [comment]
> As we are making major changes to the design of the adapter in #59 should the consistent numpy style docstring documentation be done there as part of the same PR?

If there is no documentation in #59 and you are writing documentation anyway I would recommend going for the new documentation style (don't write new documentation in the old style). However, it would be nice to not mix up things too much. Don't mix the "big documentation overhaul" into #59, since #59 on its own is already complex enough.

**Comment by IshaanDesai** [comment]
The documentation in https://github.com/precice/fenics-adapter/pull/59 is as per the old docstring format and I have been adding the changes in function arguments accordingly (this is done automatically in Pycharm). But yes mixing the entire documentation overhaul with the mid-level interface sounds too complex for one PR. I will open another PR to back up the mid-level interface with new documentation :+1:
