### ISSUE TITLE
Rename classes in expression_core.py to more meaningful names

### ISSUE THREAD

**Issue by IshaanDesai** [precice/fenics-adapter#77]
Class [CustomExpression](https://github.com/precice/fenics-adapter/blob/develop/fenicsadapter/expression_core.py#L17) can have a more meaningful name. This class creates a [FEniCS Expression](https://fenicsproject.org/docs/dolfin/1.5.0/python/programmers-reference/functions/expression/Expression.html) over the coupling interface which is the main data structure for handling evaluations at the boundary.
Possible options are: `CouplingExpression`, `BoundaryExpression`, `CouplingBoundaryExpression`

**Comment by uekerman** [comment]
I like `CouplingExpression`. Gives us the possibility to use this also for volume coupling later.

**Comment by IshaanDesai** [comment]
`CouplingExpression` also gives a good sense of what the object is! 
@ajaust comments from the user perspective?

**Comment by ajaust** [comment]
I also like `CouplingExpression`. At the moment, I do not see any conflicts with other expressions (had a quick look).

**Comment by IshaanDesai** [comment]
More renaming suggestions:
* Rename [GeneralInterpolationExpression](https://github.com/precice/fenics-adapter/blob/e951f25c8befa6c844c4e5f850ec417cfe4bc03a/fenicsadapter/expression_core.py#L145) to `RBFInterpolationExpression`
* Rename [ExactInterpolationExpression](https://github.com/precice/fenics-adapter/blob/e951f25c8befa6c844c4e5f850ec417cfe4bc03a/fenicsadapter/expression_core.py#L206) to `CubicSplineInterpolationExpression`

Both new names make it very clear to the user of what type of interpolation scheme is being used. 
Corresponding names in the tutorials repo will also be changed.
