### ISSUE TITLE
Write test to check get_point_sources functionality

### ISSUE THREAD

**Issue by IshaanDesai** [precice/fenics-adapter#84]
Functionality `get_point_sources()` needs to be tested using the mock testing framework. A test was [attempted here](https://github.com/precice/fenics-adapter/blob/4fa10b21bdb98867d41dfb94facc1c3dcfc9e743/tests/test_fenicsadapter.py#L190) but it is not as straightforward as testing the dolfin Expression functionality or the preCICE API calls. 
More details on this are provided as a `TODO` in the commented code.

**Comment by BenjaminRodenberg** [comment]
@IshaanDesai Can we close this issue? I think you implemented a test in https://github.com/precice/fenics-adapter/pull/146.

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/precice/fenics-adapter/pull/146
