### ISSUE TITLE
Provide robust initialization 

### ISSUE THREAD

**Issue by IshaanDesai** [precice/fenics-adapter#89]
Currently the user has to provide `coupling_subdomain`, `mesh` and `function_space` as mandatory arguments of `initialize`. `write_function=None`, `fixed_boundary=None` are optional arguments.

In a general FEniCS setup the read function and write function need **not** live on the same function space `V` (see [`heat.py`](https://github.com/precice/tutorials/blob/95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53/HT/partitioned-heat/fenics-fenics/heat.py#L107-L108)). The current design of the adapter assumes that the user provides the function space associated with the read function to initialize (see [`heat.py`](https://github.com/precice/tutorials/blob/95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53/HT/partitioned-heat/fenics-fenics/heat.py#L125-L132)). This prompts the need to extract additional information of the function space associated with the write function when writing data to preCICE.

A more general initialization routine can handle this smartly. The way to approach this is to use this adapter in more and more advanced FEniCS applications and modify the design by custom requirement. Parallelization of the adapter in https://github.com/precice/fenics-adapter/pull/71 already highlights such a design methodology.

Currently the same initialization routine is used if a user wants to read and write data via FEniCS Function / Expression objects or if the user wants to handle multiple `PointSource` objects. Further design ideas to differentiate these two cases need to be implemented.

**Comment by BenjaminRueth** [comment]
> This prompts the need to extract additional information of the function space associated with the write function when writing data to preCICE.

Which kind of information do you exactly mean here?

> The way to approach this is to use this adapter in more and more advanced FEniCS applications and modify the design by custom requirement.

I think we should try to make this more concrete. How do you imagine the new signature of `initialize` that fulfils all requirements? Can we already estimate what the requirements are or are there still too many unknowns? The only "advanced" example I have in mind is (of course) the heat transport tutorial. I edited your original post above and added some examples, if I was able to find good ones.
