### ISSUE TITLE
Create a simple structure solver in FEniCS and a corresponding tutorial

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#9]
Currently this is just a very rough idea, but something in the direction of our already existing FSI tutorials would be very nice.

* [SU2-CalculiX](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/SU2-CalculiX)
* [OpenFOAM-CalculiX](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX)
* 3D tube test case
* Lid Driven Cavity with flexible bottom (see https://github.com/precice/fluent-adapter/issues/2)
* many more...

Necessary steps:

- [x] Implement a simple FEM Structure solver in FEniCS
- [x] Implement one of already existing tutorials with FEniCS as structure participant
- [ ] set up 3D tube example

**Comment by uekerman** [comment]
I recommend to set up an example with OpenFOAM, not with SU2. Maybe directly our main FSI3 tutorial, which will come soon.

**Comment by BenjaminRueth** [comment]
@richahert solved the first two todos in his thesis. Refer to #38 and https://github.com/precice/tutorials/pull/38. We still do not cover the 3D tube example.

**Comment by BenjaminRueth** [comment]
@uekerman the *set up 3D tube example* should either be dropped entirely or we can open a new issue in https://github.com/precice/tutorials and close this one. What do you think?

**Comment by IshaanDesai** [comment]
FEniCS can be used as a versatile 2D structure solver using the new design of the `fenics-adapter` here: https://github.com/precice/fenics-adapter/pull/59. Do we still plan to pursue the _3D tube example_? If not then we can close this issue.

**Comment by BenjaminRueth** [comment]
Note that by now there is also a 3D Tube tutorial that uses OpenFOAM & Calculix: https://github.com/precice/tutorials/pull/23
