### ISSUE TITLE
Remove deprecated package fenicsadapter

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenics-adapter#97]
f9e2943 added a deprecation warning and a fix, if users are still using `fenicsadapter` (see #93). We should remove this deprecated package at some point in time, but might want to keep it until our users have moved to `fenicsprecice`.

**Comment by BenjaminRueth** [comment]
Related: https://github.com/precice/tutorials/pull/113

**Comment by uekerman** [comment]
I suggest to only support `fenicsprecice` for the v1.0 release. I don't really see a reason why we should keep the backwards compatibility then. We we release the adapter, we need to release the tutorials anyway.

**Comment by BenjaminRodenberg** [comment]
> I suggest to only support `fenicsprecice` for the v1.0 release. I don't really see a reason why we should keep the backwards compatibility then. We we release the adapter, we need to release the tutorials anyway.

@uekerman Even though v2.0.0 is far away in the future: This breaking change belongs to `v2.0.0`, correct? Or did I misunderstand something.

**Comment by uekerman** [comment]
> @uekerman Even though v2.0.0 is far away in the future: This breaking change belongs to v2.0.0, correct? Or did I misunderstand something.

For v1.0, the official package name is `fenicsprecice`, right? `fenicsadapter` was v0.x. So the "break" is already in the past?

**Comment by BenjaminRodenberg** [comment]
> > @uekerman Even though v2.0.0 is far away in the future: This breaking change belongs to v2.0.0, correct? Or did I misunderstand something.
> 
> For v1.0, the official package name is `fenicsprecice`, right? `fenicsadapter` was v0.x. So the "break" is already in the past?

Also good. The sooner we can get rid of it the better ;)

**Comment by BenjaminRodenberg** [comment]
Just realized this PR was linked to the wrong milestone. See discussion above.
